env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'jest-dom'
  - 'testing-library'
  - 'plugin:testing-library/recommended'
  - 'plugin:testing-library/react'
  - 'plugin:jest-dom/recommended'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  '@typescript-eslint/ban-ts-comment': off
  'jest-dom/prefer-checked': 'error'
  'jest-dom/prefer-enabled-disabled': 'error'
  'jest-dom/prefer-required': 'error'
  'jest-dom/prefer-to-have-attribute': 'error'
  'prettier/prettier': error
  'testing-library/await-async-query': 'error'
  'testing-library/no-await-sync-query': 'error'
  'testing-library/no-debug': 'warn'
